"""
Phase 1 — AI Integration Completion tests.

Proves that every provider-consuming AI path uses the active provider adapter
(not Anthropic-only logic) for all supported providers:
  - anthropic
  - google
  - openai
  - opencode-go

All external HTTP calls are mocked via unittest.mock; no real API keys are needed.
"""
from __future__ import annotations

import json
import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

from app.models.user import User
from app.models.organization import Organization, OrganizationMember, OrgMemberStatus, OrgMemberRole
from app.models.project import Project, SourceType
from app.models.document import Document, Section, SectionStatus, LifecycleStatus, SectionContentLifecycle
from app.models.ai_credential import UserAiCredential
from app.services import crypto_service
from app.services.ai_doc_service import AIService
from app.services.ai_service import AiServiceError

pytestmark = pytest.mark.anyio

# ── Helpers ──────────────────────────────────────────────────────────────────

PROVIDERS = [
    ("anthropic", "claude-sonnet-4-20250514"),
    ("google", "gemini-2.0-flash"),
    ("openai", "gpt-5"),
    ("opencode-go", "deepseek-v4-flash"),
]


def _fake_complete_text(system: str, user: str, provider: str, api_key: str, model_id: str, **kwargs) -> str:
    """Synchronous mock that returns valid JSON for all providers."""
    return json.dumps({"content": f"Generated by {provider}/{model_id}", "confidence_score": 80})


# ── Unit-level tests (no DB needed) ──────────────────────────────────────────


class TestAiServiceProviderAdapter:
    """Ensure ai_service.complete_text dispatches to all supported providers."""

    @patch("app.services.ai_service._complete_anthropic", return_value="anthropic ok")
    def test_complete_text_routes_anthropic(self, mock_fn):
        from app.services.ai_service import complete_text
        with patch("app.services.ai_service.validate_credential"):
            result = complete_text("sys", "user", "anthropic", "sk-ant-test1234", "claude-sonnet-4-20250514")
        assert result == "anthropic ok"
        mock_fn.assert_called_once()

    @patch("app.services.ai_service._complete_google", return_value="google ok")
    def test_complete_text_routes_google(self, mock_fn):
        from app.services.ai_service import complete_text
        with patch("app.services.ai_service.validate_credential"):
            result = complete_text("sys", "user", "google", "AIzatest1234", "gemini-2.0-flash")
        assert result == "google ok"
        mock_fn.assert_called_once()

    @patch("app.services.ai_service._complete_openai", return_value="openai ok")
    def test_complete_text_routes_openai(self, mock_fn):
        from app.services.ai_service import complete_text
        with patch("app.services.ai_service.validate_credential"):
            result = complete_text("sys", "user", "openai", "sk-test1234", "gpt-5")
        assert result == "openai ok"
        mock_fn.assert_called_once()

    @patch("app.services.ai_service._complete_opencode_go", return_value="opencode-go ok")
    def test_complete_text_routes_opencode_go(self, mock_fn):
        from app.services.ai_service import complete_text
        with patch("app.services.ai_service.validate_credential"):
            result = complete_text("sys", "user", "opencode-go", "oc-test1234", "deepseek-v4-flash")
        assert result == "opencode-go ok"
        mock_fn.assert_called_once()

    def test_complete_text_unsupported_provider_raises(self):
        from app.services.ai_service import complete_text, AiServiceError
        with pytest.raises(AiServiceError, match="Unsupported provider"):
            complete_text("sys", "user", "unknown-vendor", "key", "model")

    @patch("app.services.ai_service._complete_google", side_effect=ValueError("boom"))
    def test_complete_text_wraps_provider_errors(self, mock_fn):
        from app.services.ai_service import complete_text, AiServiceError
        with pytest.raises(AiServiceError, match="Could not complete google request"):
            complete_text("sys", "user", "google", "AIza-test1234", "gemini-2.0-flash")
        mock_fn.assert_called_once()

    def test_validate_credential_rejects_invalid_provider(self):
        from app.services.ai_service import validate_credential, AiServiceError
        with pytest.raises(AiServiceError, match="Unsupported provider"):
            validate_credential("badprovider", "key12345", "somemodel")

    def test_validate_credential_rejects_invalid_model(self):
        from app.services.ai_service import validate_credential, AiServiceError
        with pytest.raises(AiServiceError, match="Unsupported model"):
            validate_credential("anthropic", "key12345", "not-a-real-model")

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    def test_is_valid_model_all_providers(self, provider, model):
        from app.ai_providers import is_valid_model
        assert is_valid_model(provider, model) is True

    def test_is_valid_model_rejects_cross_provider(self):
        from app.ai_providers import is_valid_model
        # Anthropic model should not validate against Google
        assert is_valid_model("google", "claude-sonnet-4-20250514") is False


# ── No Anthropic-only gate in ai_doc_service ─────────────────────────────────


class TestNoAnthropicOnlyGate:
    """The AIService class must not reject non-Anthropic providers."""

    def test_ai_doc_service_has_no_anthropic_only_check(self):
        """Verify _get_anthropic_client method no longer exists in AIService."""
        service = AIService()
        # The gate that rejected non-Anthropic providers was in _get_anthropic_client.
        # That method should have been removed.
        assert not hasattr(service, "_get_anthropic_client"), (
            "_get_anthropic_client still exists on AIService. "
            "Remove it — it enforces an Anthropic-only gate."
        )

    def test_ai_doc_service_has_provider_neutral_credential_helper(self):
        """AIService must expose _get_active_credential, which is provider-neutral."""
        service = AIService()
        assert hasattr(service, "_get_active_credential")
        assert hasattr(service, "_complete_with_active_provider")


# ── Integration-style: complete_with_active_provider picks up active cred ────


class TestCompleteWithActiveProvider:
    """_complete_with_active_provider must dispatch through complete_text for any provider."""

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    async def test_dispatches_for_all_providers(self, provider, model):
        service = AIService()
        db = MagicMock(spec=AsyncSession)

        from app.services.ai_credential_service import ActiveCredential
        fake_cred = ActiveCredential(id=1, provider=provider, model_id=model, api_key="testkey12345")

        with (
            patch.object(service, "_get_active_credential", new=AsyncMock(return_value=fake_cred)),
            patch("app.services.ai_doc_service.complete_text", return_value='{"content":"ok","confidence_score":75}') as mock_complete,
        ):
            result = await service._complete_with_active_provider(
                db, user_id=1, system="sys", user="user", max_tokens=100
            )

        assert result == '{"content":"ok","confidence_score":75}'
        mock_complete.assert_called_once_with(
            "sys", "user", provider, "testkey12345", model, max_tokens=100
        )

    async def test_raises_http_exception_on_ai_service_error(self):
        from fastapi import HTTPException
        service = AIService()
        db = MagicMock(spec=AsyncSession)

        from app.services.ai_credential_service import ActiveCredential
        fake_cred = ActiveCredential(id=1, provider="google", model_id="gemini-2.0-flash", api_key="key")

        with (
            patch.object(service, "_get_active_credential", new=AsyncMock(return_value=fake_cred)),
            patch("app.services.ai_doc_service.complete_text", side_effect=AiServiceError("quota exceeded")),
        ):
            with pytest.raises(HTTPException) as exc_info:
                await service._complete_with_active_provider(
                    db, user_id=1, system="sys", user="user", max_tokens=100
                )
        assert exc_info.value.status_code == 400
        assert "quota exceeded" in exc_info.value.detail


# ── generate_section uses _complete_with_active_provider (all providers) ─────

class TestGenerateSectionAllProviders:
    """generate_section must not have any Anthropic-only fork."""

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    async def test_generate_section_all_providers(self, provider, model):
        """generate_section should succeed for any provider when complete_text is mocked."""
        service = AIService()
        db = AsyncMock(spec=AsyncSession)

        # Build minimal mock objects
        mock_project = MagicMock()
        mock_project.id = 1
        mock_project.name = "Test"
        mock_project.description = "Desc"
        mock_project.deleted_at = None
        mock_project.context_md = None

        mock_section = MagicMock()
        mock_section.id = 10
        mock_section.heading = "Introduction"
        mock_section.document_id = 5
        mock_section.workflow_metadata = {}

        mock_document = MagicMock()
        mock_document.id = 5
        mock_document.project_id = 1
        mock_document.template_id = None

        # Patch DB fetches
        db.execute = AsyncMock()
        db.execute.return_value.scalar_one_or_none = MagicMock(
            side_effect=[mock_project, mock_section, mock_document, None, None]
        )

        from app.services.ai_credential_service import ActiveCredential
        fake_cred = ActiveCredential(id=1, provider=provider, model_id=model, api_key="testkey12345")

        section_json = json.dumps({"content": f"Content from {provider}", "confidence_score": 70})

        with (
            patch.object(service, "_fetch_project", new=AsyncMock(return_value=mock_project)),
            patch.object(service, "_fetch_section", new=AsyncMock(return_value=mock_section)),
            patch.object(service, "_fetch_document", new=AsyncMock(return_value=mock_document)),
            patch.object(service, "_fetch_latest_analysis", new=AsyncMock(return_value=None)),
            patch.object(service, "_get_template_prompt", new=AsyncMock(return_value=None)),
            patch.object(service, "_get_active_credential", new=AsyncMock(return_value=fake_cred)),
            patch("app.services.ai_doc_service.complete_text", return_value=section_json),
        ):
            content, confidence = await service.generate_section(
                project_id=1,
                section_id=10,
                db=db,
                user_id=1,
            )

        assert f"Content from {provider}" in content
        assert confidence == 70


# ── refine_section uses _complete_with_active_provider (all providers) ──────

class TestRefineSectionAllProviders:
    """refine_section must work for any provider."""

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    async def test_refine_section_all_providers(self, provider, model):
        service = AIService()

        mock_section = MagicMock()
        mock_section.id = 10
        mock_section.heading = "Architecture"
        mock_section.document_id = 5
        mock_section.content_md = "original content"

        mock_document = MagicMock()
        mock_document.id = 5
        mock_document.project_id = 1
        mock_document.template_id = None

        mock_project = MagicMock()
        mock_project.id = 1
        mock_project.name = "Test"
        mock_project.context_md = None

        from app.services.ai_credential_service import ActiveCredential
        fake_cred = ActiveCredential(id=1, provider=provider, model_id=model, api_key="testkey12345")

        db = AsyncMock(spec=AsyncSession)

        with (
            patch.object(service, "_fetch_section", new=AsyncMock(return_value=mock_section)),
            patch.object(service, "_fetch_project", new=AsyncMock(return_value=mock_project)),
            patch.object(service, "_get_template_prompt", new=AsyncMock(return_value=None)),
            patch.object(service, "_get_active_credential", new=AsyncMock(return_value=fake_cred)),
            patch("app.services.ai_doc_service.complete_text", return_value=f"refined by {provider}"),
        ):
            # We need to also mock the document fetch inside refine_section
            db.execute = AsyncMock()
            db.execute.return_value.scalar_one_or_none = MagicMock(return_value=mock_document)

            result = await service.refine_section(
                section_id=10,
                instruction="Make it better",
                db=db,
                user_id=1,
            )

        assert f"refined by {provider}" in result["refined"]
        assert result["original"] == "original content"


# ── stream_chat falls back to complete_text for non-Anthropic providers ──────

class TestStreamChatNonAnthropic:
    """For Google and OpenCode Go, stream_chat must emit via complete_text, not Anthropic SDK."""

    @pytest.mark.parametrize("provider,model", [
        ("google", "gemini-2.0-flash"),
        ("opencode-go", "deepseek-v4-flash"),
    ])
    async def test_stream_chat_non_anthropic_uses_complete_text(self, provider, model):
        service = AIService()
        db = AsyncMock(spec=AsyncSession)

        from app.models.chat import ChatThread, ChatMessage, MessageRole
        mock_thread = MagicMock(spec=ChatThread)
        mock_thread.id = 1
        mock_thread.project_id = 1
        mock_thread.title = "Test thread"
        mock_thread.document_id = None

        mock_project = MagicMock()
        mock_project.id = 1
        mock_project.name = "Test"
        mock_project.context_md = None
        mock_project.deleted_at = None

        from app.services.ai_credential_service import ActiveCredential
        fake_cred = ActiveCredential(id=1, provider=provider, model_id=model, api_key="testkey12345")

        async def fake_get_cred(db, user_id, model_name=None):
            return fake_cred

        # Mock DB execute to return thread, then messages
        call_count = [0]
        def make_execute_side_effect():
            def side_effect(*args, **kwargs):
                call_count[0] += 1
                mock_result = MagicMock()
                if call_count[0] == 1:
                    # thread fetch
                    mock_result.scalar_one_or_none = MagicMock(return_value=mock_thread)
                elif call_count[0] == 2:
                    # user message add (commit call is separate)
                    mock_result.scalar_one_or_none = MagicMock(return_value=None)
                else:
                    # recent messages
                    mock_result.scalars.return_value.all = MagicMock(return_value=[])
                return mock_result
            return side_effect

        db.execute = AsyncMock(side_effect=make_execute_side_effect())
        db.add = MagicMock()
        db.commit = AsyncMock()

        with (
            patch.object(service, "_get_active_credential", new=AsyncMock(return_value=fake_cred)),
            patch.object(service, "_fetch_project", new=AsyncMock(return_value=mock_project)),
            patch.object(service, "_fetch_latest_analysis", new=AsyncMock(return_value=None)),
            patch.object(service, "_get_template_prompt", new=AsyncMock(return_value=None)),
            patch("app.services.ai_doc_service.complete_text", return_value=f"Response from {provider}") as mock_complete,
        ):
            gen = await service.stream_chat(
                thread_id=1,
                user_message="hello",
                db=db,
                user_id=1,
            )
            chunks = []
            async for chunk in gen:
                chunks.append(chunk)

        full = "".join(chunks)
        assert f"Response from {provider}" in full
        mock_complete.assert_called_once()
        call_kwargs = mock_complete.call_args
        assert call_kwargs.args[2] == provider  # provider arg


# ── phrasing_suggestions (all providers) ─────────────────────────────────────

class TestPhrasingSuggestionsAllProviders:
    """phrasing_suggestions must work for any provider."""

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    async def test_phrasing_suggestions_all_providers(self, provider, model):
        service = AIService()
        db = AsyncMock(spec=AsyncSession)

        mock_section = MagicMock()
        mock_section.id = 10
        mock_section.heading = "Overview"

        from app.services.ai_credential_service import ActiveCredential
        fake_cred = ActiveCredential(id=1, provider=provider, model_id=model, api_key="testkey12345")

        with (
            patch.object(service, "_fetch_section", new=AsyncMock(return_value=mock_section)),
            patch.object(service, "_get_active_credential", new=AsyncMock(return_value=fake_cred)),
            patch(
                "app.services.ai_doc_service.complete_text",
                return_value='["Professional variant", "Academic variant", "Concise variant"]',
            ),
        ):
            result = await service.phrasing_suggestions(
                section_id=10,
                text_fragment="some text",
                db=db,
                user_id=1,
            )

        assert len(result) == 3
        assert "Professional variant" in result


# ── generate_outline_with_ai (all providers via complete_text) ───────────────

class TestGenerateOutlineAllProviders:
    """generate_outline_with_ai must route through ai_service.complete_text for all providers."""

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    def test_generate_outline_with_ai_all_providers(self, provider, model):
        from app.services.analysis_service import generate_outline_with_ai, AnalysisArtifacts

        fake_artifacts = AnalysisArtifacts(
            file_tree_json={"name": "/", "type": "dir", "children": []},
            languages_json={"primary": ["python"], "breakdown": [{"language": "python", "percent": 100}], "shallow": []},
            endpoints_json={"count": 3, "items": [], "frameworks": ["fastapi"]},
            complexity_json={"total_files": 10, "largest_files": [{"path": "main.py", "lines": 200}]},
            dependencies_json=[],
        )
        template_sections = [{"heading": "Overview", "description": "", "order_index": 0}]
        expected_outline = [{"heading": "Overview", "description": "desc", "order_index": 0}]

        with patch(
            "app.services.analysis_service.ai_service.complete_text",
            return_value=json.dumps(expected_outline),
        ) as mock_complete:
            result = generate_outline_with_ai(provider, "testkey12345", model, template_sections, fake_artifacts)

        assert len(result) >= 1
        assert result[0]["heading"] == "Overview"
        mock_complete.assert_called_once_with(
            mock_complete.call_args.args[0],  # system
            mock_complete.call_args.args[1],  # user
            provider,
            "testkey12345",
            model,
        )


# ── generation_service: _generate_section_content works for all providers ────

class TestGenerationServiceAllProviders:
    """_generate_section_content must work for all providers in PROVIDER_PARALLELISM."""

    def test_provider_parallelism_has_all_providers(self):
        from app.services.generation_service import PROVIDER_PARALLELISM
        assert "anthropic" in PROVIDER_PARALLELISM
        assert "google" in PROVIDER_PARALLELISM
        assert "openai" in PROVIDER_PARALLELISM
        assert "opencode-go" in PROVIDER_PARALLELISM

    def test_model_pricing_has_all_providers(self):
        from app.services.generation_service import MODEL_PRICING_PER_1K
        assert "anthropic" in MODEL_PRICING_PER_1K
        assert "google" in MODEL_PRICING_PER_1K
        assert "opencode-go" in MODEL_PRICING_PER_1K

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    def test_cost_calculation_all_providers(self, provider, model):
        from app.services.generation_service import _cost
        cost = _cost(provider, model, 1000, 500)
        assert isinstance(cost, float)
        assert cost >= 0.0

    @pytest.mark.parametrize("provider,model", PROVIDERS)
    async def test_generate_section_content_all_providers(self, provider, model):
        """_generate_section_content should not raise for any of the three providers."""
        from app.services.generation_service import _generate_section_content, GenerationRun
        db = AsyncMock(spec=AsyncSession)

        mock_run = MagicMock(spec=GenerationRun)
        mock_run.id = 1

        mock_section = MagicMock(spec=Section)
        mock_section.id = 10
        mock_section.heading = "Overview"
        mock_section.document_id = 5
        mock_section.workflow_metadata = {}

        mock_document = MagicMock(spec=Document)
        mock_document.id = 5
        mock_document.project_id = 1

        db.get = AsyncMock(return_value=mock_document)

        section_json = json.dumps({"content": f"Content from {provider}", "confidence_score": 70})

        with patch("app.services.generation_service.ai_service.generate_section", new=AsyncMock(return_value=(f"Content from {provider}", 70))):
            result = await _generate_section_content(
                db, mock_run, mock_section, user_id=1, provider=provider, model=model
            )

        assert f"Content from {provider}" in result.content_md
        assert result.provider == provider
        assert result.model == model


# ── Error message quality ─────────────────────────────────────────────────────

class TestErrorMessages:
    """Provider errors must give users actionable messages."""

    def test_no_active_credential_message_is_provider_neutral(self):
        """The 'no credential' error must not say 'Anthropic' specifically."""
        from app.services.ai_doc_service import AIService
        import inspect
        source = inspect.getsource(AIService._get_active_credential)
        assert "Anthropic" not in source, (
            "_get_active_credential still mentions 'Anthropic'. "
            "The message must be provider-neutral."
        )

    def test_ai_service_error_unsupported_provider_is_clear(self):
        from app.services.ai_service import AiServiceError, validate_credential
        with pytest.raises(AiServiceError) as exc_info:
            validate_credential("badprovider", "key12345", "model")
        assert "provider" in exc_info.value.args[0].lower()

    def test_ai_service_error_unsupported_model_is_clear(self):
        from app.services.ai_service import AiServiceError, validate_credential
        with pytest.raises(AiServiceError) as exc_info:
            validate_credential("anthropic", "key12345", "not-a-real-claude-model")
        assert "model" in exc_info.value.args[0].lower()
