"""add_lifecycle_and_confidence_to_sections

Revision ID: db6069edf9b0
Revises: 639ab4ce20a6
Create Date: 2026-06-03 04:05:48.601203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6069edf9b0'
down_revision: Union[str, None] = '639ab4ce20a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE lifecyclestatus AS ENUM ('ACTIVE', 'DELETED', 'ARCHIVED')")
    op.add_column('sections', sa.Column('title', sa.String(), nullable=True))
    op.add_column('sections', sa.Column('is_custom', sa.Boolean(), nullable=True))
    op.add_column('sections', sa.Column('lifecycle_status', sa.Enum('ACTIVE', 'DELETED', 'ARCHIVED', name='lifecyclestatus'), nullable=True))
    op.execute("UPDATE sections SET lifecycle_status = 'ACTIVE'")
    op.alter_column('sections', 'lifecycle_status', nullable=False)
    op.add_column('sections', sa.Column('confidence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'confidence_score')
    op.drop_column('sections', 'lifecycle_status')
    op.execute("DROP TYPE lifecyclestatus")
    op.drop_column('sections', 'is_custom')
    op.drop_column('sections', 'title')
    # ### end Alembic commands ###
