"""add_quality_export_tables

Revision ID: c46e3db3196c
Revises: d4e5f6a7b8c9
Create Date: 2026-05-30 02:44:53.581520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46e3db3196c'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('readability', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_quality_reports_project_id')
    )
    op.create_index(op.f('ix_quality_reports_id'), 'quality_reports', ['id'], unique=False)
    op.create_table('broken_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('section_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['quality_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broken_links_id'), 'broken_links', ['id'], unique=False)
    op.create_table('quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', 'INFO', name='issueseverity'), nullable=False),
    sa.Column('section_ref', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['quality_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issues_id'), 'quality_issues', ['id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_threads_project_id'), table_name='chat_threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_threads_project_id'), 'chat_threads', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_quality_issues_id'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_broken_links_id'), table_name='broken_links')
    op.drop_table('broken_links')
    op.drop_index(op.f('ix_quality_reports_id'), table_name='quality_reports')
    op.drop_table('quality_reports')
    # ### end Alembic commands ###
