"""Add source ingestion models

Revision ID: da7bd75bc677
Revises: c455b695615a
Create Date: 2026-05-22 07:48:19.646262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7bd75bc677'
down_revision: Union[str, None] = 'c455b695615a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('git_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'git_provider')
    # ### end Alembic commands ###
