"""add nlp_reports, export_settings, org_ai_fields

Revision ID: 16f966427c1e
Revises: 45c70e705693
Create Date: 2026-06-04 03:07:20.701892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f966427c1e'
down_revision: Union[str, None] = '45c70e705693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nlp_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('style_analysis', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlp_reports_id'), 'nlp_reports', ['id'], unique=False)
    op.add_column('organizations', sa.Column('ai_provider', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('ai_key_encrypted', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('export_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'export_settings')
    op.drop_column('organizations', 'ai_key_encrypted')
    op.drop_column('organizations', 'ai_provider')
    op.drop_index(op.f('ix_nlp_reports_id'), table_name='nlp_reports')
    op.drop_table('nlp_reports')
    # ### end Alembic commands ###
