"""add_multi_tenancy

Revision ID: 57499f703718
Revises: c46e3db3196c
Create Date: 2026-05-30 15:55:50.094068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57499f703718'
down_revision: Union[str, None] = 'c46e3db3196c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='true', nullable=False))
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('personal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_user_api_keys_key_hash'), 'user_api_keys', ['key_hash'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROJECT_MANAGER', 'DEVELOPER', 'TECHNICAL_WRITER', 'VIEWER', name='orgmemberrole'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', name='orgmemberstatus'), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=True),
    sa.Column('invite_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_invite_token'), 'organization_members', ['invite_token'], unique=False)

    op.add_column('projects', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_projects_organizations', 'projects', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key('fk_projects_users_created_by', 'projects', 'users', ['created_by'], ['id'])

    # --- Data Migration ---
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, name FROM users")).fetchall()

    for user in users:
        user_id, user_name = user
        slug = f"user-{user_id}-workspace"

        # Create personal org
        connection.execute(
            sa.text("INSERT INTO organizations (name, slug, created_by, created_at, personal) "
                    "VALUES (:name, :slug, :created_by, NOW(), true)"),
            {"name": f"{user_name}'s Workspace", "slug": slug, "created_by": user_id}
        )

        org_id = connection.execute(
            sa.text("SELECT id FROM organizations WHERE slug = :slug"),
            {"slug": slug}
        ).scalar()

        # Member
        connection.execute(
            sa.text("INSERT INTO organization_members (org_id, user_id, role, joined_at, status) "
                    "VALUES (:org_id, :user_id, 'ADMIN', NOW(), 'ACTIVE')"),
            {"org_id": org_id, "user_id": user_id}
        )

        # Mark verified
        connection.execute(
            sa.text("UPDATE users SET is_verified = true WHERE id = :id"),
            {"id": user_id}
        )

        # Map projects
        connection.execute(
            sa.text("UPDATE projects SET org_id = :org_id, created_by = :user_id WHERE owner_id = :user_id"),
            {"org_id": org_id, "user_id": user_id}
        )

    # Now finalize schema
    op.drop_column('projects', 'owner_id')
    op.alter_column('projects', 'org_id', nullable=False)
    op.alter_column('projects', 'created_by', nullable=False)

    op.add_column('user_settings', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_settings_verification_token'), 'user_settings', ['verification_token'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_user_settings_verification_token'), table_name='user_settings')
    op.drop_column('user_settings', 'verification_token_expires')
    op.drop_column('user_settings', 'verification_token')
    op.add_column('projects', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_projects_users_created_by', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_organizations', 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'org_id')
    op.drop_index(op.f('ix_organization_members_invite_token'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_api_keys_key_hash'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
