"""add analysis_data to analyses

Revision ID: 6417c63228da
Revises: 57499f703718
Create Date: 2026-06-02 23:20:49.184942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6417c63228da'
down_revision: Union[str, None] = '57499f703718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('analysis_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'analysis_data')
    # ### end Alembic commands ###
