"""add tagging, review workflow, notes, quality threshold

Revision ID: 45c70e705693
Revises: db6069edf9b0
Create Date: 2026-06-04 00:21:23.627114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c70e705693'
down_revision: Union[str, None] = 'db6069edf9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE documentstatus AS ENUM ('DRAFT', 'IN_REVIEW', 'APPROVED')")
    op.create_table('collaboration_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_notes_id'), 'collaboration_notes', ['id'], unique=False)
    op.add_column('documents', sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', name='documentstatus', create_type=False), nullable=False, server_default='DRAFT'))
    op.add_column('documents', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['reviewer_id'], ['id'])
    op.add_column('organizations', sa.Column('quality_threshold', sa.Integer(), nullable=False, server_default='70'))
    op.add_column('projects', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE documentstatus")
    op.drop_column('projects', 'tags')
    op.drop_column('organizations', 'quality_threshold')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'approved_at')
    op.drop_column('documents', 'reviewer_id')
    op.drop_column('documents', 'status')
    op.drop_index(op.f('ix_collaboration_notes_id'), table_name='collaboration_notes')
    op.drop_table('collaboration_notes')
    # ### end Alembic commands ###
