"""add_system_prompt_to_templates

Revision ID: a02e532a9692
Revises: 16f966427c2f
Create Date: 2026-06-04 18:50:07.623862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02e532a9692'
down_revision: Union[str, None] = '16f966427c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'system_prompt')
    # ### end Alembic commands ###
